ATArticle = 0
ATString = 1
ATBasePrice = 2
ATReleased = 3
ATEmblemPrices = 4
AHat = 0
AGlasses = 1
ABackpack = 2
AShoes = 3
ABoysHat = 4
ABoysGlasses = 5
ABoysBackpack = 6
ABoysShoes = 7
AGirlsHat = 8
AGirlsGlasses = 9
AGirlsBackpack = 10
AGirlsShoes = 11
APriceTest = 5
APriceBasic = 250
APriceBasicPlus = 500
APriceCool = 800
APriceAwesome = 1500
ATokenPriceBasic = 10
ATokenPriceBasicPlus = 30
ATokenPriceCool = 50
ATokenPriceAwesome = 100
ATokenPriceAmazing = 250
AccessoryTypes = {101: (AHat,
       'hbb1',
       APriceBasic,
       1),
 102: (AHat,
       'hsf1',
       APriceCool,
       5),
 103: (AHat,
       'hrb1',
       APriceBasic,
       1),
 104: (AHat,
       'hsf2',
       APriceCool,
       0),
 105: (AHat,
       'hsf3',
       APriceCool,
       0),
 106: (AHat,
       'hrb2',
       APriceBasicPlus,
       3),
 107: (AHat,
       'hrb3',
       APriceBasicPlus,
       0),
 108: (AHat,
       'hht1',
       APriceCool,
       4),
 109: (AHat,
       'hht2',
       APriceCool,
       3),
 110: (AHat,
       'htp1',
       APriceCool,
       3),
 111: (AHat,
       'htp2',
       APriceCool,
       0),
 112: (AHat,
       'hav1',
       3500,
       0),
 113: (AHat,
       'hfp1',
       3500,
       0),
 114: (AHat,
       'hsg1',
       3500,
       0),
 115: (AHat,
       'hwt1',
       3500,
       0),
 116: (AHat,
       'hsf4',
       APriceCool,
       0),
 117: (AHat,
       'hgf1',
       APriceCool,
       1),
 118: (AHat,
       'hpt1',
       APriceBasicPlus,
       1),
 119: (AHat,
       'hpt3',
       APriceBasicPlus,
       1),
 120: (AHat,
       'hcr1',
       10000,
       5),
 121: (AHat,
       'hbb2',
       APriceBasic,
       2),
 122: (AHat,
       'hbb3',
       APriceBasic,
       2),
 123: (AHat,
       'hcw1',
       APriceCool,
       1),
 124: (AHat,
       'hpr1',
       APriceAwesome,
       1),
 125: (AHat,
       'hpp1',
       APriceBasicPlus,
       1),
 126: (AHat,
       'hfs1',
       APriceCool,
       1),
 127: (AHat,
       'hpt4',
       APriceCool,
       9),
 128: (AHat,
       'hst1',
       APriceBasicPlus,
       1),
 129: (AHat,
       'hsu1',
       APriceCool,
       1),
 130: (AHat,
       'hrb4',
       APriceBasic,
       1),
 131: (AHat,
       'hrb5',
       APriceBasicPlus,
       4),
 132: (AHat,
       'hrb6',
       APriceBasic,
       2),
 133: (AHat,
       'hrb7',
       APriceBasicPlus,
       6),
 134: (AHat,
       'hat1',
       APriceCool,
       2),
 135: (AHat,
       'hhd1',
       APriceCool,
       2),
 136: (AHat,
       'hbw1',
       APriceCool,
       6),
 137: (AHat,
       'hch1',
       APriceCool,
       5),
 138: (AHat,
       'hdt1',
       APriceAwesome,
       6),
 139: (AHat,
       'hft1',
       APriceCool,
       4),
 140: (AHat,
       'hfd1',
       APriceCool,
       6),
 141: (AHat,
       'hmk1',
       APriceAwesome,
       2),
 142: (AHat,
       'hft2',
       APriceCool,
       6),
 143: (AHat,
       'hhd2',
       APriceCool,
       3),
 144: (AHat,
       'hpc1',
       APriceCool,
       5),
 145: (AHat,
       'hrh1',
       APriceCool,
       2),
 146: (AHat,
       'hhm1',
       2500,
       2),
 147: (AHat,
       'hat2',
       APriceCool,
       2),
 148: (AHat,
       'htr1',
       5000,
       3),
 149: (AHat,
       'htr2',
       5000,
       3),
 150: (AHat,
       'hwz1',
       APriceCool,
       2),
 151: (AHat,
       'hwz2',
       APriceCool,
       2),
 152: (AHat,
       'hwz3',
       APriceCool,
       2),
 153: (AHat,
       'hhm4',
       APriceAwesome,
       5),
 154: (AHat,
       'hfp2',
       APriceCool,
       5),
 155: (AHat,
       'hhm5',
       APriceAwesome,
       4),
 156: (AHat,
       'hnp1',
       APriceAwesome,
       6),
 157: (AHat,
       'hpc2',
       APriceAwesome,
       3),
 158: (AHat,
       'hwh1',
       APriceCool,
       4),
 159: (AHat,
       'hwh2',
       APriceCool,
       4),
 160: (AHat,
       'hbb4',
       APriceBasic,
       5),
 161: (AHat,
       'hbb5',
       APriceBasic,
       2),
 162: (AHat,
       'hbb6',
       APriceBasic,
       5),
 163: (AHat,
       'hsl1',
       APriceCool,
       5),
 164: (AHat,
       'hfr1',
       3000,
       4),
 165: (AHat,
       'hby1',
       APriceAwesome,
       5),
 166: (AHat,
       'hrb8',
       APriceBasicPlus,
       6),
 167: (AHat,
       'hjh1',
       APriceAwesome,
       3),
 168: (AHat,
       'hbb7',
       APriceBasic,
       6),
 169: (AHat,
       'hrb9',
       APriceBasicPlus,
       6),
 170: (AHat,
       'hwt2',
       APriceAwesome,
       4),
 171: (AHat,
       'hhw1',
       APriceBasicPlus,
        7),
 172: (AHat,
       'hhw2',
       900,
       7),
 173: (AHat,
       'hob1',
       APriceAwesome,
       6),
 174: (AHat,
       'hbn1',
       APriceAwesome,
       8),
 175: (AHat,
       'hpt2',
       APriceCool,
       9),
 176: (AHat,
       'hwh3',
       APriceBasicPlus,
       4),
 177: (AHat,
       'hwh4',
       APriceBasicPlus,
       4),
 178: (AHat,
       'hwh5',
       APriceBasic,
       4),
 179: (AHat,
       'hwh6',
       APriceBasic,
       4),
 180: (AHat,
       'htp3',
       ATokenPriceAmazing,
       4),
 181: (AHat,
       'hrb10',
       ATokenPriceAwesome,
       4),
 182: (AHat,
       'hrb11',
       ATokenPriceBasic,
       4),
 183: (AHat,
       'hrb12',
       ATokenPriceBasicPlus,
       4),
 185: (AHat,
       'hrb14',
       ATokenPriceBasicPlus,
       4),
 186: (AHat,
       'hrb15',
       ATokenPriceBasicPlus,
       4),
 187: (AHat,
       'hrb16',
       ATokenPriceBasicPlus,
       4),
 188: (AHat,
       'hrb17',
       ATokenPriceCool,
       4),
 189: (AHat,
       'hrb18',
       ATokenPriceCool,
       4),
 190: (AHat,
       'hrb19',
       ATokenPriceCool,
       4),
 191: (AHat,
       'hrb20',
       ATokenPriceCool,
       4),
 192: (AHat,
       'hsu2',
       ATokenPriceBasicPlus,
       4),
 193: (AHat,
       'hgf2',
       ATokenPriceCool,
       4),
 194: (AHat,
       'hwh7',
       APriceBasic,
       4),
 195: (AHat,
       'hwh8',
       APriceBasicPlus,
       4),
 196: (AHat,
       'hwh9',
       APriceCool,
       4),
 201: (AGlasses,
       'grd1',
       APriceBasicPlus,
       0),
 202: (AGlasses,
       'gmb1',
       APriceCool,
       1),
 203: (AGlasses,
       'gnr1',
       APriceCool,
       0),
 204: (AGlasses,
       'gst1',
       APriceBasicPlus,
       1),
 205: (AGlasses,
       'g3d1',
       APriceCool,
       1),
 206: (AGlasses,
       'gav1',
       APriceCool,
       1),
 207: (AGlasses,
       'gce1',
       APriceCool,
       2),
 208: (AGlasses,
       'gdk1',
       APriceBasic,
       1),
 209: (AGlasses,
       'gwh1',
       APriceAwesome,
       1),
 210: (AGlasses,
       'gwh2',
       APriceAwesome,
       1),
 211: (AGlasses,
       'gdk2',
       APriceBasic,
       1),
 212: (AGlasses,
       'ggm1',
       APriceBasicPlus,
       2),
 213: (AGlasses,
       'ghg1',
       APriceAwesome,
       3),
 214: (AGlasses,
       'gie1',
       APriceCool,
       2),
 215: (AGlasses,
       'gmt1',
       APriceCool,
       2),
 216: (AGlasses,
       'gmt2',
       APriceCool,
       2),
 217: (AGlasses,
       'gmt3',
       3500,
       5),
 218: (AGlasses,
       'gmt4',
       3500,
       5),
 219: (AGlasses,
       'gmt5',
       3500,
       5),
 220: (AGlasses,
       'gmn1',
       APriceAwesome,
       6),
 221: (AGlasses,
       'gmo1',
       APriceAwesome,
       4),
 222: (AGlasses,
       'gsr1',
       APriceBasicPlus,
       5),
 223: (AGlasses,
       'ghw1',
       APriceBasicPlus,
       0),
 224: (AGlasses,
       'ghw2',
       APriceBasicPlus,
       7),
 225: (AGlasses,
       'gdk3',
       ATokenPriceBasic,
       1),
 226: (AGlasses,
       'gdk4',
       ATokenPriceBasicPlus,
       1),
 227: (AGlasses,
       'gdk5',
       ATokenPriceBasicPlus,
       1),
 228: (AGlasses,
       'gdk6',
       ATokenPriceBasic,
       1),
 229: (AGlasses,
       'gdk7',
       ATokenPriceBasicPlus,
       1),
 230: (AGlasses,
       'gdk8',
       ATokenPriceBasicPlus,
       1),
 231: (AGlasses,
       'gdk9',
       ATokenPriceBasicPlus,
       1),
 232: (AGlasses,
       'gdk10',
       ATokenPriceBasic,
       1),
 233: (AGlasses,
       'gdk11',
       ATokenPriceBasic,
       1),
 234: (AGlasses,
       'gdk12',
       ATokenPriceBasic,
       1),
 235: (AGlasses,
       'gdk13',
       ATokenPriceBasicPlus,
       1),
 236: (AGlasses,
       'gdk14',
       ATokenPriceBasicPlus,
       1),
 237: (AGlasses,
       'gag1',
       ATokenPriceCool,
       1),
 238: (AGlasses,
       'gnr2',
       ATokenPriceBasic,
       1),
 239: (AGlasses,
       'gnr3',
       ATokenPriceBasic,
       1),
 240: (AGlasses,
       'gnr4',
       ATokenPriceBasic,
       1),
 241: (AGlasses,
       'gnr5',
       ATokenPriceBasic,
       1),
 242: (AGlasses,
       'gnr6',
       ATokenPriceBasic,
       1),
 243: (AGlasses,
       'gwh3',
       APriceBasicPlus,
       0),
 301: (ABackpack,
       'bpb1',
       APriceBasic,
       4),
 302: (ABackpack,
       'bpb2',
       APriceBasic,
       1),
 303: (ABackpack,
       'bpb3',
       APriceBasic,
       5),
 304: (ABackpack,
       'bpd1',
       APriceBasicPlus,
       4),
 305: (ABackpack,
       'bpd2',
       APriceBasicPlus,
       5),
 306: (ABackpack,
       'bwh1',
       APriceCool,
       2),
 307: (ABackpack,
       'bwh2',
       APriceCool,
       2),
 308: (ABackpack,
       'bwh3',
       APriceCool,
       2),
 309: (ABackpack,
       'bst1',
       APriceAwesome,
       1),
 310: (ABackpack,
       'bfn1',
       'bwh4',
       APriceCool,
       1),
 311: (ABackpack,
       'baw1',
       APriceCool,
       3),
 312: (ABackpack,
       'baw2',
       APriceAwesome,
       2),
 313: (ABackpack,
       'bwt1',
       3000,
       3),
 314: (ABackpack,
       'bwg4',
       APriceAwesome,
       6),
 315: (ABackpack,
       'bwg5',
       3000,
       5),
 316: (ABackpack,
       'bwg6',
       3000,
       4),
 317: (ABackpack,
       'bjp1',
       3000,
       1),
318: (ABackpack,
       'blg1',
       APriceCool,
       2),
 319: (ABackpack,
       'bsa1',
       2500,
       5),
320: (ABackpack,
       'bwg7',
       APriceAwesome,
       6),
 321: (ABackpack,
       'bsa2',
       2000,
       2),
 322: (ABackpack,
       'bsa3',
       2000,
       2),
323: (ABackpack,
       'bap1',
       5000,
       4),
 324: (ABackpack,
       'bhw1',
       900,
       7),
 325: (ABackpack,
       'bhw2',
       APriceBasicPlus,
       7),
 326: (ABackpack,
       'bhw3',
       APriceBasicPlus,
       7),
 327: (ABackpack,
       'bhw4',
       900,
       7),
328: (ABackpack,
       'bob1',
       3000,
       6),
 329: (ABackpack,
       'bfg1',
       3000,
       6),
 330: (ABackpack,
       'bfl1',
       APriceAwesome,
       8),
 331: (ABackpack,
       'bjar',
       APriceAwesome,
       9),
 332: (ABackpack,
       'bga1',
       ATokenPriceAwesome,
       1),
 333: (ABackpack,
       'bbt1',
       ATokenPriceAwesome,
       1),
 334: (ABackpack,
       'bbt2',
       ATokenPriceBasic,
       1),
 335: (ABackpack,
       'bbt3',
       ATokenPriceBasicPlus,
       1),
 337: (ABackpack,
       'bbt5',
       ATokenPriceBasicPlus,
       1),
 338: (ABackpack,
       'bbt6',
       ATokenPriceBasicPlus,
       1),
 339: (ABackpack,
       'bbt7',
       ATokenPriceBasicPlus,
       1),
 340: (ABackpack,
       'bbt8',
       ATokenPriceCool,
       1),
 341: (ABackpack,
       'bbt9',
       ATokenPriceCool,
       1),
 342: (ABackpack,
       'bbt10',
       ATokenPriceCool,
       1),
 343: (ABackpack,
       'bbt11',
       ATokenPriceCool,
       1),
 344: (ABackpack,
       'bcp2',
       ATokenPriceCool,
       1),
 345: (ABackpack,
       'bcp3',
       ATokenPriceCool,
       1),
 346: (ABackpack,
       'bjar',
       ATokenPriceAmazing,
       1),
 347: (ABackpack,
       'bwh5',
       APriceCool,
       2),
 348: (ABackpack,
       'bwh6',
       APriceCool,
       2),
 349: (ABackpack,
       'brb1',
       APriceCool,
       2),
 350: (ABackpack,
       'brb2',
       APriceCool,
       2),
 351: (ABackpack,
       'brb3',
       APriceCool,
       2),
 352: (ABackpack,
       'brb4',
       APriceCool,
       2),
 353: (ABackpack,
       'brb5',
       APriceCool,
       2),
 354: (ABackpack,
       'brb6',
       APriceCool,
       2),
 355: (ABackpack,
       'brb7',
       APriceCool,
       2),
 356: (ABackpack,
       'brb8',
       APriceCool,
       2),
 401: (AShoes,
       'sat1',
       APriceBasic,
       3),
 402: (AShoes,
       'sat2',
       APriceBasic,
       1),
 403: (AShoes,
       'smb1',
       APriceAwesome,
       1),
 404: (AShoes,
       'scs1',
       APriceBasicPlus,
       6),
 405: (AShoes,
       'swt1',
       APriceBasicPlus,
       1),
 406: (AShoes,
       'smj1',
       APriceBasicPlus,
       1),
 407: (AShoes,
       'sdk1',
       APriceBasic,
       1),
 408: (AShoes,
       'sat3',
       APriceBasic,
       1),
 409: (AShoes,
       'scs2',
       APriceBasicPlus,
       1),
 410: (AShoes,
       'scs3',
       APriceBasicPlus,
       1),
 411: (AShoes,
       'scs4',
       APriceBasicPlus,
       1),
 412: (AShoes,
       'scb1',
       APriceAwesome,
       1),
 413: (AShoes,
       'sfb1',
       APriceCool,
       1),
 414: (AShoes,
       'sht1',
       APriceAwesome,
       4),
 415: (AShoes,
       'smj2',
       APriceBasicPlus,
       3),
 416: (AShoes,
       'smj3',
       APriceBasicPlus,
       4),
 417: (AShoes,
       'ssb1',
       APriceAwesome,
       2),
 418: (AShoes,
       'sts1',
       APriceBasic,
       5),
 419: (AShoes,
       'sts2',
       APriceBasic,
       4),
 420: (AShoes,
       'scs5',
       APriceBasicPlus,
       4),
 421: (AShoes,
       'smb2',
       APriceAwesome,
       3),
 422: (AShoes,
       'smb3',
       APriceAwesome,
       2),
 423: (AShoes,
       'smb4',
       APriceAwesome,
       5),
 424: (AShoes,
       'sfb2',
       2000,
       6),
 425: (AShoes,
       'sfb3',
       2000,
       4),
 426: (AShoes,
       'sfb4',
       2000,
       3),
 427: (AShoes,
       'sfb5',
       2000,
       5),
 428: (AShoes,
       'sfb6',
       2000,
       4),
 429: (AShoes,
       'slf1',
       APriceBasicPlus,
       3),
 430: (AShoes,
       'smj4',
       APriceBasicPlus,
       2),
 431: (AShoes,
       'smt1',
       APriceAwesome,
       4),
 432: (AShoes,
       'sox1',
       APriceAwesome,
       5),
 433: (AShoes,
       'srb1',
       APriceAwesome,
       6),
 434: (AShoes,
       'sst1',
       3000,
       3),
 435: (AShoes,
       'swb1',
       APriceCool,
       3),
 436: (AShoes,
       'swb2',
       APriceCool,
       4),
 437: (AShoes,
       'swk1',
       APriceAwesome,
       3),
 438: (AShoes,
       'scs6',
       APriceBasicPlus,
       0),
 439: (AShoes,
       'smb5',
       APriceAwesome,
       3),
 440: (AShoes,
       'sht2',
       APriceAwesome,
       4),
 441: (AShoes,
       'srb2',
       APriceAwesome,
       3),
 442: (AShoes,
       'sts3',
       APriceBasic,
       6),
 443: (AShoes,
       'sts4',
       APriceBasic,
       3),
 444: (AShoes,
       'sts5',
       APriceBasic,
       2),
 445: (AShoes,
       'srb3',
       APriceCool,
       5),
 446: (AShoes,
       'srb4',
       APriceCool,
       3),
 447: (AShoes,
       'sat4',
       APriceBasic,
       3),
 448: (AShoes,
       'shw1',
       APriceCool,
       7),
 449: (AShoes,
       'shw2',
       APriceCool,
       7),
 450: (AShoes,
       'stf1',
       APriceAwesome,
       9),
 451: (AShoes,
       'stf2',
       APriceAwesome,
       9),
 452: (AShoes,
       'stf3',
       APriceAwesome,
       9),
 453: (AShoes,
       'stf4',
       APriceAwesome,
       9),
 454: (AShoes,
       'sjs1',
       APriceCool,
       1),
 455: (AShoes,
       'sch1',
       APriceBasic,
       1),
 456: (AShoes,
       'sch2',
       APriceBasic,
       1),
 457: (AShoes,
       'swh3',
       APriceBasic,
       1),
 458: (AShoes,
       'swh4',
       APriceBasic,
       1),
 459: (AShoes,
       'swh5',
       APriceBasic,
       1)}
LoyaltyAccessoryItems = []
